In [1]:
from utils import sparse_to_adjlist
from scipy.io import loadmat
import pickle

In [2]:
prefix = 'data/'

yelp = loadmat('data/YelpChi.mat')
net_rur = yelp['net_rur']
net_rtr = yelp['net_rtr']
net_rsr = yelp['net_rsr']
yelp_homo = yelp['homo']
features = yelp['features']
label = yelp['label']

In [3]:
yelp

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Wed Aug 19 20:09:02 2020',
 '__version__': '1.0',
 '__globals__': [],
 'homo': <45954x45954 sparse matrix of type '<class 'numpy.float64'>'
 	with 7693958 stored elements in Compressed Sparse Column format>,
 'net_rur': <45954x45954 sparse matrix of type '<class 'numpy.float64'>'
 	with 98630 stored elements in Compressed Sparse Column format>,
 'net_rtr': <45954x45954 sparse matrix of type '<class 'numpy.float64'>'
 	with 1147232 stored elements in Compressed Sparse Column format>,
 'net_rsr': <45954x45954 sparse matrix of type '<class 'numpy.float64'>'
 	with 6805486 stored elements in Compressed Sparse Column format>,
 'features': <45954x32 sparse matrix of type '<class 'numpy.float64'>'
 	with 1469088 stored elements in Compressed Sparse Column format>,
 'label': array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)}

In [4]:
import numpy as np
# 读取 npz 文件
data = np.load('E:\pythonProject\Fraud_Detection\data.npz', allow_pickle=True)
print(list(data.keys()))

['x', 'y', 'edge_type', 'edge_index', 'train_mask', 'test_mask']


In [5]:
data['y']

array([   1,    1,    1, ...,    0, -100,    0], dtype=int64)

In [6]:
data['x']

array([[ 0.00000000e+00,  6.00000000e+00, -1.00000000e+00, ...,
        -1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  3.00000000e+00, -1.00000000e+00, ...,
        -1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  5.00000000e+00, -1.00000000e+00, ...,
        -1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       ...,
       [ 1.00000000e+00,  4.00000000e+00, -1.00000000e+00, ...,
        -1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  3.00000000e+00, -1.00000000e+00, ...,
        -1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 1.00000000e+00,  4.00000000e+00,  1.01000000e+00, ...,
         8.57142857e-01,  4.95049505e-03,  1.42857143e-01]])

In [7]:
data['edge_type']

array([ 6,  5,  6, ..., 11,  9, 10], dtype=int64)

In [8]:
edge_types = data['edge_type']

# 使用 np.unique 统计每个元素的个数
unique_elements, counts = np.unique(edge_types, return_counts=True)

# 将结果放入字典
counts_dict = dict(zip(unique_elements, counts))

# 输出每种元素的个数
for element, count in counts_dict.items():
    print(f"Edge Type {element}: {count} occurrences")

Edge Type 1: 18766 occurrences
Edge Type 2: 1758 occurrences
Edge Type 3: 2949 occurrences
Edge Type 4: 35076 occurrences
Edge Type 5: 63909 occurrences
Edge Type 6: 26108 occurrences
Edge Type 7: 107 occurrences
Edge Type 8: 5044 occurrences
Edge Type 9: 5589 occurrences
Edge Type 10: 5493 occurrences
Edge Type 11: 2760 occurrences


In [9]:
data['edge_index']

array([[410472,  19609],
       [205686, 359744],
       [469991, 488834],
       ...,
       [241907, 450710],
       [577465, 210486],
       [308446, 335478]], dtype=int64)

In [10]:
import scipy.sparse as sp

In [11]:
with open("E:\pythonProject\Fraud_Detection\extended_graphs_data.pkl", "rb") as file:
    d = pickle.load(file)
    file.close()

In [12]:
dense_matrix = d.x
sparse_matrix = sp.csr_matrix(dense_matrix)
print(sparse_matrix)

  (0, 1)	6.0
  (0, 34)	1.0
  (0, 35)	1.0
  (0, 36)	1.0
  (0, 37)	1.0
  (0, 38)	1.0
  (0, 39)	1.0
  (0, 40)	1.0
  (0, 41)	1.0
  (0, 43)	1.0
  (0, 44)	1.0
  (0, 45)	1.0
  (0, 46)	1.0
  (0, 47)	1.0
  (0, 48)	1.0
  (1, 1)	3.0
  (1, 34)	1.0
  (1, 35)	1.0
  (1, 36)	1.0
  (1, 37)	1.0
  (1, 38)	1.0
  (1, 39)	1.0
  (1, 40)	1.0
  (1, 41)	1.0
  (1, 43)	1.0
  :	:
  (579155, 41)	1.0
  (579155, 43)	1.0
  (579155, 44)	1.0
  (579155, 45)	1.0
  (579155, 46)	1.0
  (579155, 47)	1.0
  (579155, 48)	1.0
  (579155, 49)	1.0
  (579156, 0)	1.0
  (579156, 1)	4.0
  (579156, 2)	1.01
  (579156, 3)	0.83
  (579156, 4)	0.8217822
  (579156, 5)	0.7
  (579156, 6)	2.451
  (579156, 7)	0.039
  (579156, 8)	2.41
  (579156, 9)	0.98327214
  (579156, 10)	1.0
  (579156, 11)	0.17821783
  (579156, 12)	0.016727867
  (579156, 13)	0.042168673
  (579156, 14)	0.85714287
  (579156, 15)	0.004950495
  (579156, 16)	0.14285715


In [13]:
edge_type = data['edge_type']
edge_index = data['edge_index']

adj_matrix = sp.coo_matrix((edge_type.flatten(), (edge_index[:, 0], edge_index[:, 1])),
                           shape=(579157, 579157),
                           dtype=np.float32)
print(adj_matrix)

  (410472, 19609)	6.0
  (205686, 359744)	5.0
  (469991, 488834)	6.0
  (186516, 172498)	1.0
  (380073, 60100)	1.0
  (380073, 30305)	5.0
  (412851, 463368)	11.0
  (445156, 500952)	1.0
  (434388, 240028)	5.0
  (477700, 330803)	4.0
  (359022, 468600)	4.0
  (167283, 215248)	6.0
  (365311, 62743)	5.0
  (122233, 567623)	5.0
  (487327, 159648)	5.0
  (540681, 443492)	5.0
  (459250, 251885)	5.0
  (346598, 121439)	5.0
  (292022, 91877)	6.0
  (292022, 483375)	6.0
  (321909, 121701)	5.0
  (321909, 221874)	5.0
  (79858, 554266)	6.0
  (416052, 147542)	5.0
  (266412, 87102)	6.0
  :	:
  (219830, 253783)	11.0
  (575226, 559172)	10.0
  (27518, 69931)	9.0
  (471501, 135349)	11.0
  (411845, 244809)	9.0
  (200084, 330993)	9.0
  (328413, 477630)	10.0
  (476264, 26617)	9.0
  (243335, 439795)	9.0
  (115260, 119652)	9.0
  (412966, 4320)	11.0
  (17360, 230372)	11.0
  (474848, 301574)	9.0
  (474848, 412294)	9.0
  (573138, 516079)	10.0
  (332648, 213792)	9.0
  (83801, 134475)	11.0
  (37033, 214153)	10.0
  (205249,

In [14]:
num_edge_types = 11
# 初始化三个稀疏矩阵
net_rur = sp.coo_matrix(([], ([], [])), shape=(579157, 579157), dtype=np.float32)
net_rtr = sp.coo_matrix(([], ([], [])), shape=(579157, 579157), dtype=np.float32)
net_rsr = sp.coo_matrix(([], ([], [])), shape=(579157, 579157), dtype=np.float32)

c1 = [2,3,7,11]
c2 = [1,8,9,10]
c3 = [4,5,6]

# 根据边的类型将边分为三类
for i in range(1, num_edge_types + 1):
    indices = np.where(edge_type == i)[0]
    
    if i in c1:
        net_rur += sp.coo_matrix((np.ones_like(indices), (edge_index[indices, 0], edge_index[indices, 1])),
                                 shape=(579157, 579157),
                                 dtype=np.float32)
    elif i in c2:
        net_rtr += sp.coo_matrix((np.ones_like(indices), (edge_index[indices, 0], edge_index[indices, 1])),
                                 shape=(579157, 579157),
                                 dtype=np.float32)
    elif i in c3:
        net_rsr += sp.coo_matrix((np.ones_like(indices), (edge_index[indices, 0], edge_index[indices, 1])),
                                 shape=(579157, 579157),
                                 dtype=np.float32)

In [15]:
net_rur

<579157x579157 sparse matrix of type '<class 'numpy.float32'>'
	with 7574 stored elements in Compressed Sparse Row format>

In [16]:
net_rtr

<579157x579157 sparse matrix of type '<class 'numpy.float32'>'
	with 34892 stored elements in Compressed Sparse Row format>

In [17]:
net_rsr

<579157x579157 sparse matrix of type '<class 'numpy.float32'>'
	with 125093 stored elements in Compressed Sparse Row format>

In [18]:
from scipy.io import savemat

# Create a dictionary to store your data with appropriate keys
data_dict = {
    'homo': adj_matrix,
    'net_rur': net_rur,
    'net_rtr': net_rtr,
    'net_rsr': net_rsr,
    'features': sparse_matrix,
    'label': data['y']
}

# Provide the desired file name for your .mat file
file_name = 'fraud.mat'

# Save the data to the .mat file
savemat(file_name, data_dict)

print(f"Data saved to {file_name}")

Data saved to fraud.mat


In [19]:
mat = loadmat(file_name)

In [20]:
mat

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Thu Dec 21 14:46:00 2023',
 '__version__': '1.0',
 '__globals__': [],
 'homo': <579157x579157 sparse matrix of type '<class 'numpy.float32'>'
 	with 167559 stored elements in Compressed Sparse Column format>,
 'net_rur': <579157x579157 sparse matrix of type '<class 'numpy.float32'>'
 	with 7574 stored elements in Compressed Sparse Column format>,
 'net_rtr': <579157x579157 sparse matrix of type '<class 'numpy.float32'>'
 	with 34892 stored elements in Compressed Sparse Column format>,
 'net_rsr': <579157x579157 sparse matrix of type '<class 'numpy.float32'>'
 	with 125093 stored elements in Compressed Sparse Column format>,
 'features': <579157x50 sparse matrix of type '<class 'numpy.float32'>'
 	with 9990475 stored elements in Compressed Sparse Column format>,
 'label': array([[   1,    1,    1, ...,    0, -100,    0]], dtype=int64)}